jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_PASSWORD}

spring:
  application:
    name: auth
  datasource:
    url: ENC(K01jNbcKIUljwo98YtS9qJ5e3PiC2ioQe97fNSKeJ/k9uTVqIgmicqU4NPOHWZjxRIuML2uFRKAXglsCWOizVDH8vHZwmdHGuGaoomTORvE=)
    username: ENC(XhGT41xwg0J9hSXkV9tPjQ==)
    password: ENC(cOWaniGDoCFEXR9v+wRBVEwsJ5Hg6vQN)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

oauth:
  kakao:
    client-id: ENC(Bt6eM/fhddJAPXSptpWF3mUjdR6Sf//6w6W9q65IOPS2dp7qOByivWaW5ljFqi7O)
    client-secret: ENC(UkF9iKVwNwfMRDbTqGrrotqxiG75OUOpr0x4z7C52hPBqvkghp5A7bwXdU/aekTD)
    redirect-uri: http://localhost:8888/v1/auth
jwt:
  secret: ENC(bkvH+mRzgfeLK4bZDHmcbfa5etKqItNkUaXmRn7NIFALSTudUWKlDTinBnbU+JYECrp+l/qnofo=)
  access-token-expiration: ENC(ch/UXDWKupu5PnMpcI3DEg==)
  refresh-token-expiration: ENC(/T++6ZbhvDUhaZgscOQ/oKJZzHHk3VQ9)

client:
  base:
    url: ENC(6r5+iURZyGrnWE3rn4C1XXhxZpzilbAqGkb4WdQs0fijyMzoZxHRhA==)